config/routes.rb
Rails.application.routes.draw do
  # get 'items/index'
  # get 'items/show'
  # get 'items/new'
  # get 'items/create'
  get 'users/show'

  devise_for :users

  resources :users do
      resources :items, only: [:new, :create, :destroy]
  end

  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  get 'welcome/about'

  root 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :items
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        root_path
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        @item.user = current_user

        if @item.save
          flash[:notice] = "To-Do has been saved."
          redirect_to root_path
        else
          flash.now[:alert] = "There was an issue saving your To-Do."
          render :new
        end
    end

    def destroy
        @item = Item.find(params[:id])

        if @item.destroy
            flash[:notice] = "\"#{@item.name}\" was deleted sucessfully."
            redirect_to root_path
        else
            flash.now[:alert] = "There was an error deleting the Wiki."
            render root_path
        end
    end

    private
    def item_params
        params.require(:item).permit(:name)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  POST /resource
  def create
    super
    p "for the love of god"
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = current_user

      if !user_signed_in?
          redirect_to welcome_index_path
      end 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [item] do |f| %>
    <div class="col-md-6">
        <p>Reminders for Your To-Dos</p>
        <ul>
            <li>Each To-Do will disappear from your list if you don't complete it!</li>
            <li>Anyone can see your To-Do list...peer pressure is a great motivator!</li>
            <li>Life is busy, but this tool can help you accomplish your goals.</li>
        </ul>
    </div>
    <div class="col-md-6">
        <%= form_for @item do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control', placeholder: "Enter your To-Do" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success'%>
            </div>
        <% end %>
    </div>
<% end %>

app/views/items/_item.html.erb
<div class="row">
    <div class="col-md-8">
        <% @user.items.each do |item| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= item.name %>
                        <%= "Created " + distance_of_time_in_words(Time.now, item.created_at, include_seconds: true) + " ago"  %>
                        <%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok' %>
                    </h4>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/new.html.erb
<h1>New To-Do</h1>

<div class="row">
    <%= render partial: 'form', locals: { item: @item } %>
</div>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ToDoKaBoom</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="pull-left"><%= link_to "Home", welcome_index_path, :class => 'navbar-link' %></li>
                <% if user_signed_in? %>
                    <li class="pull-left"><%= link_to "To-Do List", root_path, :class => 'navbar-link' %></li>
                    <li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
                    <li class="pull-right"><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %></li>
                <% else %>
                    <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
                    <li class="pull-right"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
                <% end %>
            </ul>
        <% if flash[:notice] %>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
            </div>
        <% elsif flash[:alert] %>
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
            </div>
        <% end %>

            <%= yield %>
        </div>
    </body>
</html>

app/views/users/show.html.erb
<h2>Here Are Your To-Dos, <%="#{current_user.email}"%>...Get Crackin!!!!!</h2>

<div class="row">
    <div class="col-md-8">
        <%= render partial: 'items/item', locals: { item: @item } %>
    </div>
    <% if current_user %>
        <div class="col-md-4">
            <%= link_to "New To-Do", new_item_path, class: 'btn btn-success' %>
        </div>
    <% end %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>